name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 仅在打 tag 时触发构建和发布
  workflow_dispatch:  # 保留手动触发选项

# 设置权限，允许创建 Release
permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      
      - name: 获取 pnpm store 目录
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      
      - name: 设置 pnpm 缓存
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      
      - name: 下载 FFmpeg (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          echo "=== 下载 FFmpeg for macOS ==="
          brew install ffmpeg
          mkdir -p resources/ffmpeg/mac
          cp $(which ffmpeg) resources/ffmpeg/mac/ffmpeg
          cp $(which ffprobe) resources/ffmpeg/mac/ffprobe
          chmod +x resources/ffmpeg/mac/ffmpeg
          chmod +x resources/ffmpeg/mac/ffprobe
          ls -lh resources/ffmpeg/mac/
      
      - name: 下载 FFmpeg (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Write-Host "=== 下载 FFmpeg for Windows ==="
          $url = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
          $output = "$env:TEMP\ffmpeg.zip"
          Write-Host "下载中..."
          Invoke-WebRequest -Uri $url -OutFile $output
          Write-Host "解压中..."
          Expand-Archive -Path $output -DestinationPath "$env:TEMP\ffmpeg" -Force
          $ffmpegDir = Get-ChildItem -Path "$env:TEMP\ffmpeg" -Directory | Select-Object -First 1
          Write-Host "找到 FFmpeg 目录: $($ffmpegDir.FullName)"
          New-Item -ItemType Directory -Force -Path "resources\ffmpeg\win"
          Copy-Item "$($ffmpegDir.FullName)\bin\ffmpeg.exe" "resources\ffmpeg\win\"
          Copy-Item "$($ffmpegDir.FullName)\bin\ffprobe.exe" "resources\ffmpeg\win\"
          Get-ChildItem -Path "resources\ffmpeg\win\" | ForEach-Object { Write-Host "$($_.Name): $([math]::Round($_.Length / 1MB, 2)) MB" }
      
      - name: 构建应用
        run: pnpm run build
      
      - name: 检查构建输出
        shell: bash
        run: |
          echo "=== 检查 dist 目录结构 ==="
          find dist -type f -name "*.js" | head -20
          echo "=== 检查入口文件 ==="
          ls -la dist/main/main/index.js || echo "入口文件不存在"
      
      - name: 打包应用 (macOS)
        if: matrix.os == 'macos-latest'
        run: pnpm run package:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 打包应用 (Windows)
        if: matrix.os == 'windows-latest'
        run: pnpm run package:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 上传构建产物 (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: VideoTool-macOS
          path: release/
          if-no-files-found: warn
      
      - name: 上传构建产物 (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: VideoTool-Windows
          path: release/
          if-no-files-found: warn
  
  release:
    name: 创建 Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: VideoTool-*
          merge-multiple: false
      
      - name: 显示构建产物
        run: ls -R artifacts
      
      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/VideoTool-macOS/**/*.dmg
            artifacts/VideoTool-Windows/**/VideoTool Setup*.exe
          fail_on_unmatched_files: false

